# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f04e50c4852c10c6872ef658ca176da"
name = "Tokengate (dev)"
handle = "tokengate-dev"
application_url = "https://ltd-uk-candles-vehicles.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "dev-test-basics.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_gates,write_discounts,write_gates,write_products"

[auth]
redirect_urls = [
  "https://ltd-uk-candles-vehicles.trycloudflare.com/auth/callback",
  "https://ltd-uk-candles-vehicles.trycloudflare.com/auth/shopify/callback",
  "https://ltd-uk-candles-vehicles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
